name: "Release"

on:
    push:
        tags:
            - "v*"

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
    CARGO_TERM_COLOR: always

jobs:
    build:
        name: Build
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: moonrepo/setup-rust@v1
              with:
                  channel: stable
                  cache-base: "^master$"
            - run: cargo build

    fmt-check:
        name: Format Check
        runs-on: ubuntu-latest
        continue-on-error: true # avoid failing CI for trivial formatting errors
        steps:
            - uses: actions/checkout@v5
            - uses: moonrepo/setup-rust@v1
              with:
                  channel: nightly
                  components: rustfmt
                  cache-base: "^master$"
            - run: cargo fmt --check

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: moonrepo/setup-rust@v1
              with:
                  channel: stable
                  components: clippy
                  cache-base: "^master$"
            - run: cargo clippy

    publish:
        name: Publish
        needs: [build, lint]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: moonrepo/setup-rust@v1
              with:
                  channel: stable
                  cache-base: "^master$"
            - run: "cargo publish --token $CARGO_TOKEN"

    tagged-release:
        needs: [build, publish, lint]
        permissions:
            id-token: write
            contents: write
            packages: write
        runs-on: ubuntu-latest
        steps:
            - uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false

    # test:
    #     name: Test
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v5
    #           with:
    #               fetch-depth: 0
    #         - uses: moonrepo/setup-rust@v1
    #           with:
    #               bins: cargo-nextest
    #               channel: nightly
    #               cache-base: "^master$"
    #         - run: "cargo nextest run --workspace --no-tests=pass --retries=2"
